project:
  type: website
  
execute:
  freeze: auto  # re-render only when source changes

website:
  title: "Publication Ready Graphs and Tables in R (SDDRC)"
  navbar:
    left:
      - href: index.qmd
        text: Introduction
      - href: ggplot2.qmd
        text: "Plots and Graphs"
      - href: gt.qmd
        text: "Tables"
      - href: gtsummary.qmd
        text: "Tables for Models"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



