project:
  type: website
  output-dir: docs
  
execute:
  freeze: auto  # re-render only when source changes

website:
  title: "Publication Ready Graphs and Tables in R (SDDRC)"
  page-navigation: true
  back-to-top-navigation: true
  navbar:
    left:
      - href: index.qmd
        text: Introduction
      - href: ggplot2.qmd
        text: "Custom Plots"
      - href: stat_plots.qmd
        text: "Statistical Plots"
      - href: sequence_plots.qmd
        text: "Sequencing Plots"
      - href: gtsummary.qmd
        text: "Statistical Tables"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    html-table-processing: none


