project:
  type: website
  output-dir: docs
  
execute:
  freeze: auto  # re-render only when source changes

website:
  title: "Publication Ready Graphs and Tables in R (SDDRC)"
  navbar:
    left:
      - href: index.qmd
        text: Introduction
      - href: ggplot2.qmd
        text: "Custome Plots"
      - href: ggstatplot.qmd
        text: "Statistical Plots"
      - href: gt.qmd
        text: "Custom Tables"
      - href: gtsummary.qmd
        text: "Statistical Tables"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



